name: "Sync GitHub Labels"

on:
  push:
    paths:
      - "../ISSUE_TEMPLATE/issue-label.yml"

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels from config
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/ISSUE_TEMPLATE/issue-label.yml
